spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: flight-service
          uri: http://localhost:9001/
          predicates:
            - Path=/flights/**

        - id: user-service
          uri: http://localhost:9002/
          predicates:
            - Path=/user/**
            
        - id: admin-service
          uri: http://localhost:9003/
          predicates:
            - Path=/admin/**


server:
  port: 8081

